### ISSUE TITLE
A screenshot somewhere ?

### ISSUE THREAD

**Issue by tbarbette** [nvanggaard/clockalarm#8]
Hi,

Is this only an automation kind of component? Is there a GUI for the component? Could you extend the doc to answer that?

Thanks !

**Comment by nvanggaard** [comment]
@tbarbette I've added a link to a screenshot to the readme.

**Comment by tbarbette** [comment]
Thank you very much ! I feel like what you did is what I'm looking for ! However the screenshot is not working...

**Comment by nvanggaard** [comment]
I'm very glad you like it! 
I'm working on making a pull request to the official repository, but it takes quite some work. 

Thanks for notifying about the broken link

**Comment by nvanggaard** [comment]
The screenshot is now working.
