### ISSUE TITLE
HomeAssistant cannot find component

### ISSUE THREAD

**Issue by WheezyE** [nvanggaard/clockalarm#9]
I'm new to custom components, so I may be missing something obvious.  But I followed the directions and HASS is saying this in my log.

`2017-06-22 23:02:50 ERROR (MainThread) [homeassistant.loader] Unable to find component clockalarm`
`2017-06-22 23:02:50 ERROR (MainThread) [homeassistant.setup] Setup failed for clockalarm: Component not found.`

**Comment by WheezyE** [comment]
I figured it out: The github readme file has a typo 
`Copy the clockalarm.py into 'homeassistantfolder/custom_componenets`
should be 
`Copy the clockalarm.py into 'homeassistantfolder/custom_components`

Thank you for the great alarm clock!

**Comment by nvanggaard** [comment]
A yeah, thanks for heads up!
